export const buttonStyles = {
    primaryLarge : {
      backgroundColor: '#CFFF5E',
      textColor: '#000000',
      borderRadius: 12,
      paddingVertical: 16,
      paddingHorizontal: 32,
      fontSize: 16,
      disabledBackgroundColor: '#E8FFA1',
    },
    primaryMedium: {
        backgroundColor: '#D5FF3F',
        textColor: '#000000',
        paddingVertical: 12,
        paddingHorizontal: 28,
        borderRadius: 12,
        fontSize: 14,
        disabledBackgroundColor: '#E8FFA1',
      },
      primarySmall: {
        backgroundColor: '#D5FF3F',
        textColor: '#000000',
        paddingVertical: 8,
        paddingHorizontal: 20,
        borderRadius: 12,
        fontSize: 12,
        disabledBackgroundColor: '#E8FFA1',
      },
      primaryPressed: {
        backgroundColor: '#C488F0',
        textColor: '#000000',
        paddingVertical: 12,
        paddingHorizontal: 28,
        borderRadius: 12,
        fontSize: 14,
        disabledBackgroundColor: '#E8FFA1',
      },
      primaryDisabled: {
        backgroundColor: '#E8FFA1',
        textColor: '#C0C0C0',
        paddingVertical: 16,
        paddingHorizontal: 32,
        borderRadius: 12,
        fontSize: 16,
        disabledBackgroundColor: '#E8FFA1',
      },
      secondaryLarge: {
        backgroundColor: '#E6E8EB',
        textColor: '#222831',
        paddingVertical: 16,
        paddingHorizontal: 32,
        borderRadius: 12,
        fontSize: 16,
        disabledBackgroundColor: '#F3F4F5',
      },
      secondaryMedium: {
        backgroundColor: '#E6E8EB',
        textColor: '#222831',
        paddingVertical: 12,
        paddingHorizontal: 28,
        borderRadius: 12,
        fontSize: 14,
        disabledBackgroundColor: '#F3F4F5',
      },
      secondarySmall: {
        backgroundColor: '#E6E8EB',
        textColor: '#222831',
        paddingVertical: 8,
        paddingHorizontal: 20,
        borderRadius: 12,
        fontSize: 12,
        disabledBackgroundColor: '#F3F4F5',
      },
      secondaryPressed: {
        backgroundColor: '#C488F0',
        textColor: '#000000',
        paddingVertical: 12,
        paddingHorizontal: 28,
        borderRadius: 12,
        fontSize: 14,
        disabledBackgroundColor: '#F3F4F5',
      },
      secondaryDisabled: {
        backgroundColor: '#F3F4F5',
        textColor: '#C0C0C0',
        paddingVertical: 16,
        paddingHorizontal: 32,
        borderRadius: 12,
        fontSize: 16,
        disabledBackgroundColor: '#F3F4F5',
      },
    
  };
  