import { colors } from '../colors/colors';
import { Spacing } from '../Layout/spacing';
import { fonts } from '../typography/fonts';

export const buttonStyles = {
    primaryLarge : {
      backgroundColor: colors.primary.base,
      textColor: colors.text,
      borderRadius: 12,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.xl,
      fontSize: fonts.size.body,
      disabledBackgroundColor: colors.primary.lightest,
    },
    primaryMedium: {
        backgroundColor: colors.primary.base,
        textColor: colors.text,
        paddingVertical: Spacing.sm,
        paddingHorizontal: Spacing.lg,
        borderRadius: 12,
        fontSize: fonts.size.caption,
        disabledBackgroundColor: colors.primary.lightest,
      },
      primarySmall: {
        backgroundColor: colors.primary.base,
        textColor: colors.text,
        paddingVertical: Spacing.xs,
        paddingHorizontal: Spacing.md,
        borderRadius: 12,
        fontSize: fonts.size.caption,
        disabledBackgroundColor: colors.primary.lightest,
      },
      primaryPressed: {
        backgroundColor: colors.tertiary.base,
        textColor: colors.text,
        paddingVertical: Spacing.sm,
        paddingHorizontal: Spacing.lg,
        borderRadius: 12,
        fontSize: fonts.size.caption,
        disabledBackgroundColor: colors.primary.lightest,
      },
      primaryDisabled: {
        backgroundColor: colors.primary.lightest,
        textColor: colors.disabled,
        paddingVertical: Spacing.sm,
        paddingHorizontal: Spacing.lg,
        borderRadius: 12,
        fontSize: fonts.size.caption,
        disabledBackgroundColor: colors.primary.lightest,
      },
      secondaryLarge: {
        backgroundColor: colors.border,
        textColor: colors.text,
        paddingVertical: Spacing.md,
        paddingHorizontal: Spacing.xl,
        borderRadius: 12,
        fontSize: fonts.size.body,
        disabledBackgroundColor: colors.background,
      },
      secondaryMedium: {
        backgroundColor: colors.border,
        textColor: colors.text,
        paddingVertical: Spacing.sm,
        paddingHorizontal: Spacing.lg,
        borderRadius: 12,
        fontSize: fonts.size.caption,
        disabledBackgroundColor: colors.background,
      },
      secondarySmall: {
        backgroundColor: colors.border,
        textColor: colors.text,
        paddingVertical: Spacing.xs,
        paddingHorizontal: Spacing.md,
        borderRadius: 12,
        fontSize: fonts.size.caption,
        disabledBackgroundColor: colors.background,
      },
      secondaryPressed: {
        backgroundColor: colors.tertiary.base,
        textColor: colors.text,
        paddingVertical: Spacing.sm,
        paddingHorizontal: Spacing.lg,
        borderRadius: 12,
        fontSize: fonts.size.caption,
        disabledBackgroundColor: colors.background,
      },
      secondaryDisabled: {
        backgroundColor: colors.background,
        textColor: colors.disabled,
        paddingVertical: Spacing.sm,
        paddingHorizontal: Spacing.lg,
        borderRadius: 12,
        fontSize: fonts.size.caption,
        disabledBackgroundColor: colors.background,
      },
      iconOnlyLarge: {
        backgroundColor: 'transparent',
        textColor: colors.text,
        borderRadius: 12,
        fontSize: fonts.size.accent,
        width: 60,
        height: 60,
        borderWidth: 2,
        borderColor: colors.border,
      },
      
      iconOnlyMedium: {
        backgroundColor: 'transparent',
        textColor: colors.text,
        borderRadius: 12,
        fontSize: fonts.size.body,
        width: 48,
        height: 48,
        borderWidth: 2,
        borderColor: colors.border,
      },
      
      iconOnlySmall: {
        backgroundColor: 'transparent',
        textColor: colors.text,
        borderRadius: 12,
        fontSize: fonts.size.caption,
        width: 36,
        height: 36,
        borderWidth: 2,
        borderColor: colors.border,
      },
      
      iconOnlyPressed: {
        backgroundColor: colors.tertiary.base,
        textColor: colors.text,
        borderRadius: 12,
        iconColor: colors.text,
        fontSize: fonts.size.body,
        width: 48,
        height: 48,
        borderWidth: 2,
        borderColor: colors.border,
      },
     
      
      
      iconOnlyDisabled: {
        backgroundColor: 'transparent',
        textColor: colors.disabled,
        borderRadius: 12,
        iconColor: colors.disabled,
        fontSize: fonts.size.body,
        width: 48,
        height: 48,
        borderWidth: 2,
        borderColor: colors.border,
      },
      
      textOnlyLarge: {
        backgroundColor: 'transparent',
        textColor: colors.text,
        borderRadius: 0,
        paddingVertical: Spacing.md,
        paddingHorizontal: Spacing.sm,
        fontSize: fonts.size.body,
        disabledBackgroundColor: 'transparent',
      },
      textOnlyMedium: {
        backgroundColor: 'transparent',
        textColor: colors.text,
        borderRadius: 0,
        paddingVertical: Spacing.sm,
        paddingHorizontal: Spacing.xs,
        fontSize: fonts.size.caption,
        disabledBackgroundColor: 'transparent',
      },
      textOnlySmall: {
        backgroundColor: 'transparent',
        textColor: colors.text,
        borderRadius: 0,
        paddingVertical: Spacing.xs,
        paddingHorizontal: Spacing.xs,
        fontSize: fonts.size.caption,
        disabledBackgroundColor: 'transparent',
      },
      textOnlyPressed: {
        backgroundColor: 'transparent',
        textColor: colors.tertiary.base,
        borderRadius: 0,
        paddingVertical: Spacing.sm,
        paddingHorizontal: Spacing.xs,
        fontSize: fonts.size.caption,
        disabledBackgroundColor: 'transparent',
      },
      textOnlyDisabled: {
        backgroundColor: 'transparent',
        textColor: colors.disabled,
        borderRadius: 0,
        paddingVertical: Spacing.md,
        paddingHorizontal: Spacing.sm,
        fontSize: fonts.size.body,
        disabledBackgroundColor: 'transparent',
      },
      
    
  };
  